// Code generated by protoc-gen-go.
// source: company.proto
// DO NOT EDIT!

/*
Package company is a generated protocol buffer package.

It is generated from these files:
	company.proto

It has these top-level messages:
	CompanyItem
	Session
	CreateRequest
	CreateResponse
	DeleteRequest
	DeleteResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
*/
package company

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type CompanyItem struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Owner   string `protobuf:"bytes,3,opt,name=owner" json:"owner,omitempty"`
	About   string `protobuf:"bytes,4,opt,name=about" json:"about,omitempty"`
	Address string `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
}

func (m *CompanyItem) Reset()                    { *m = CompanyItem{} }
func (m *CompanyItem) String() string            { return proto.CompactTextString(m) }
func (*CompanyItem) ProtoMessage()               {}
func (*CompanyItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Session struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Created  int64  `protobuf:"varint,3,opt,name=created" json:"created,omitempty"`
	Expires  int64  `protobuf:"varint,4,opt,name=expires" json:"expires,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CreateRequest struct {
	Company *CompanyItem `protobuf:"bytes,1,opt,name=company" json:"company,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateRequest) GetCompany() *CompanyItem {
	if m != nil {
		return m.Company
	}
	return nil
}

type CreateResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type ReadResponse struct {
	Company *CompanyItem `protobuf:"bytes,1,opt,name=company" json:"company,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ReadResponse) GetCompany() *CompanyItem {
	if m != nil {
		return m.Company
	}
	return nil
}

type UpdateRequest struct {
	Company *CompanyItem `protobuf:"bytes,1,opt,name=company" json:"company,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateRequest) GetCompany() *CompanyItem {
	if m != nil {
		return m.Company
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*CompanyItem)(nil), "CompanyItem")
	proto.RegisterType((*Session)(nil), "Session")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Company service

type CompanyClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
}

type companyClient struct {
	c           client.Client
	serviceName string
}

func NewCompanyClient(serviceName string, c client.Client) CompanyClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "company"
	}
	return &companyClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *companyClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Company.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companyClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Company.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Company service

type CompanyHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
}

func RegisterCompanyHandler(s server.Server, hdlr CompanyHandler) {
	s.Handle(s.NewHandler(&Company{hdlr}))
}

type Company struct {
	CompanyHandler
}

func (h *Company) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.CompanyHandler.Create(ctx, in, out)
}

func (h *Company) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.CompanyHandler.Read(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x4b, 0xc4, 0x30,
	0x14, 0xdc, 0xef, 0xea, 0xeb, 0x87, 0x12, 0x3c, 0x84, 0x82, 0xb8, 0x04, 0x14, 0x41, 0xc8, 0x61,
	0x05, 0xfd, 0x01, 0xeb, 0xc5, 0x6b, 0xc5, 0xa3, 0x87, 0xec, 0xe6, 0x1d, 0x0a, 0xb6, 0xa9, 0x4d,
	0xcb, 0xea, 0xbf, 0x37, 0x4d, 0x1a, 0xed, 0xae, 0x08, 0xe2, 0xa9, 0x99, 0x79, 0x1f, 0x33, 0xf3,
	0x28, 0xc4, 0x5b, 0x55, 0x54, 0xa2, 0xfc, 0xe0, 0x55, 0xad, 0x1a, 0xc5, 0x76, 0x10, 0xae, 0x1d,
	0xf1, 0xd8, 0x60, 0x41, 0x12, 0x98, 0xe4, 0x92, 0x8e, 0x97, 0xe3, 0xeb, 0xe3, 0xcc, 0xbc, 0x08,
	0x81, 0x59, 0x29, 0x0a, 0xa4, 0x13, 0xcb, 0xd8, 0x37, 0x39, 0x83, 0xb9, 0xda, 0x95, 0x58, 0xd3,
	0xa9, 0x25, 0x1d, 0xe8, 0x58, 0xb1, 0x51, 0x6d, 0x43, 0x67, 0x8e, 0xb5, 0x80, 0x50, 0x08, 0x84,
	0x94, 0x35, 0x6a, 0x4d, 0xe7, 0x96, 0xf7, 0x90, 0xe5, 0x10, 0x3c, 0x99, 0x6f, 0xae, 0xca, 0x1f,
	0xa2, 0x29, 0x1c, 0xb5, 0x1a, 0xeb, 0x81, 0xf0, 0x17, 0xee, 0x16, 0x6e, 0x6b, 0x14, 0x0d, 0x4a,
	0x2b, 0x3f, 0xcd, 0x3c, 0xec, 0x2a, 0xf8, 0x5e, 0xe5, 0x66, 0xb9, 0xb5, 0x60, 0x2a, 0x3d, 0x64,
	0xf7, 0x10, 0xaf, 0x6d, 0x53, 0x86, 0x6f, 0x2d, 0xea, 0x86, 0x5c, 0x99, 0x25, 0x2e, 0xb4, 0x55,
	0x0d, 0x57, 0x11, 0x1f, 0x1c, 0x21, 0xf3, 0x45, 0xb6, 0x84, 0xc4, 0x0f, 0xea, 0x4a, 0x95, 0x1a,
	0x0f, 0xad, 0xb2, 0x0b, 0x88, 0x1f, 0xf0, 0x15, 0xbf, 0x57, 0x1f, 0x36, 0x9c, 0x42, 0xe2, 0x1b,
	0xdc, 0x0a, 0x76, 0x0e, 0x61, 0x86, 0x42, 0xfe, 0x36, 0x70, 0x07, 0x91, 0x2b, 0xf7, 0x8a, 0x7f,
	0xf5, 0x6a, 0x42, 0x3e, 0x57, 0xf2, 0x1f, 0x21, 0x8d, 0x43, 0x3f, 0xe8, 0x24, 0x57, 0x2f, 0x10,
	0xf4, 0x9d, 0xe4, 0x06, 0x16, 0xee, 0x02, 0x24, 0xe1, 0x7b, 0x37, 0x4c, 0x4f, 0xf8, 0xfe, 0x69,
	0xd8, 0x88, 0x5c, 0xc2, 0xac, 0xb3, 0x4e, 0x22, 0x3e, 0x08, 0x98, 0xc6, 0x7c, 0x98, 0x87, 0x8d,
	0x36, 0x0b, 0xfb, 0xe7, 0xdd, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x99, 0x83, 0xa2, 0x8a,
	0x02, 0x00, 0x00,
}
