// Code generated by protoc-gen-go.
// source: github.com/saromanov/company-service/proto/company/company.proto
// DO NOT EDIT!

/*
Package company is a generated protocol buffer package.

It is generated from these files:
	github.com/saromanov/company-service/proto/company/company.proto

It has these top-level messages:
	CompanyItem
	Session
	CreateRequest
	CreateResponse
	DeleteRequest
	DeleteResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
*/
package company

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type CompanyItem struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Owner   string `protobuf:"bytes,3,opt,name=owner" json:"owner,omitempty"`
	About   string `protobuf:"bytes,4,opt,name=about" json:"about,omitempty"`
	Address string `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
}

func (m *CompanyItem) Reset()                    { *m = CompanyItem{} }
func (m *CompanyItem) String() string            { return proto.CompactTextString(m) }
func (*CompanyItem) ProtoMessage()               {}
func (*CompanyItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Session struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Created  int64  `protobuf:"varint,3,opt,name=created" json:"created,omitempty"`
	Expires  int64  `protobuf:"varint,4,opt,name=expires" json:"expires,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CreateRequest struct {
	Company *CompanyItem `protobuf:"bytes,1,opt,name=company" json:"company,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateRequest) GetCompany() *CompanyItem {
	if m != nil {
		return m.Company
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type ReadResponse struct {
	Company *CompanyItem `protobuf:"bytes,1,opt,name=company" json:"company,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ReadResponse) GetCompany() *CompanyItem {
	if m != nil {
		return m.Company
	}
	return nil
}

type UpdateRequest struct {
	Company *CompanyItem `protobuf:"bytes,1,opt,name=company" json:"company,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateRequest) GetCompany() *CompanyItem {
	if m != nil {
		return m.Company
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*CompanyItem)(nil), "CompanyItem")
	proto.RegisterType((*Session)(nil), "Session")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
}

var fileDescriptor0 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x4b, 0x03, 0x31,
	0x14, 0xec, 0x77, 0xf5, 0xf5, 0x43, 0x09, 0x1e, 0x96, 0x82, 0x28, 0x0b, 0x8a, 0x20, 0xa6, 0x50,
	0x41, 0xaf, 0x42, 0xbd, 0x78, 0x5d, 0xf1, 0xe8, 0x21, 0x6d, 0x1e, 0x1a, 0x70, 0x93, 0x35, 0xc9,
	0xb6, 0xfa, 0xef, 0xcd, 0x26, 0x8d, 0xae, 0x15, 0x41, 0x3c, 0x6d, 0x66, 0xde, 0xc7, 0xcc, 0x3c,
	0x16, 0x6e, 0x9e, 0x84, 0x7d, 0x2e, 0x17, 0x74, 0xa9, 0xf2, 0xa9, 0x61, 0x5a, 0xe5, 0x4c, 0xaa,
	0xd5, 0xd4, 0xa1, 0x82, 0xc9, 0xf7, 0x0b, 0x83, 0x7a, 0x25, 0x96, 0x38, 0x2d, 0xb4, 0xb2, 0x2a,
	0xb2, 0xf1, 0x4b, 0x3d, 0x9b, 0xae, 0x61, 0x30, 0x0f, 0xc4, 0x9d, 0xc5, 0x9c, 0x8c, 0xa1, 0x25,
	0x78, 0xd2, 0x3c, 0x6e, 0x9e, 0xed, 0x66, 0xee, 0x45, 0x08, 0x74, 0x24, 0xcb, 0x31, 0x69, 0x79,
	0xc6, 0xbf, 0xc9, 0x01, 0x74, 0xd5, 0x5a, 0xa2, 0x4e, 0xda, 0x9e, 0x0c, 0xa0, 0x62, 0xd9, 0x42,
	0x95, 0x36, 0xe9, 0x04, 0xd6, 0x03, 0x92, 0x40, 0x9f, 0x71, 0xae, 0xd1, 0x98, 0xa4, 0xeb, 0xf9,
	0x08, 0x53, 0x01, 0xfd, 0x7b, 0xf7, 0x15, 0x4a, 0xfe, 0x10, 0x9d, 0xc0, 0x4e, 0xe9, 0xbc, 0xd7,
	0x84, 0x3f, 0x71, 0xb5, 0x70, 0xa9, 0x91, 0x59, 0xe4, 0x5e, 0xbe, 0x9d, 0x45, 0x58, 0x55, 0xf0,
	0xad, 0x10, 0x6e, 0xb9, 0xb7, 0xe0, 0x2a, 0x1b, 0x98, 0x5e, 0xc3, 0x68, 0xee, 0x9b, 0x32, 0x7c,
	0x2d, 0xd1, 0x58, 0x72, 0xea, 0x96, 0x84, 0xd0, 0x5e, 0x75, 0x30, 0x1b, 0xd2, 0xda, 0x11, 0xb2,
	0x58, 0x4c, 0xf7, 0x61, 0x1c, 0x07, 0x4d, 0xa1, 0xa4, 0xc1, 0xf4, 0x08, 0x46, 0xb7, 0xf8, 0x82,
	0x5f, 0xab, 0xb6, 0xbc, 0x57, 0x23, 0xb1, 0x61, 0x33, 0x72, 0x08, 0x83, 0x0c, 0x19, 0xff, 0x6d,
	0xe0, 0x0a, 0x86, 0xa1, 0x1c, 0xda, 0xff, 0xec, 0xcd, 0x85, 0x7a, 0x28, 0xf8, 0xff, 0x42, 0xc5,
	0xc1, 0x20, 0x39, 0x7b, 0x84, 0xfe, 0xa6, 0x93, 0x9c, 0x43, 0x2f, 0x24, 0x26, 0x63, 0xfa, 0xed,
	0x66, 0x93, 0x3d, 0xba, 0x75, 0x8a, 0x06, 0x39, 0x81, 0x4e, 0x65, 0x9d, 0x0c, 0x69, 0x2d, 0xe0,
	0x64, 0x44, 0xeb, 0x79, 0xd2, 0xc6, 0xa2, 0xe7, 0xff, 0xb4, 0xcb, 0x8f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x53, 0x85, 0x07, 0xbd, 0xad, 0x02, 0x00, 0x00,
}
